# fly.toml app configuration file generated for short-stories-api on 2025-04-05T21:26:39+11:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'short-stories-api'
primary_region = 'syd'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
